/*
 * generated by Xtext
 */
package dk.itu.mdd.policyengine.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PeDslUiModule extends dk.itu.mdd.policyengine.ui.AbstractPeDslUiModule {
	public PeDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
