/**
 * generated by Xtext
 */
package dk.itu.mdd.policyengine.validation;

import dk.itu.mdd.policyengine.validation.AbstractPolicyEngineDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PolicyEngineDslValidator extends AbstractPolicyEngineDslValidator {
}
