/**
 * generated by Xtext
 */
package dk.itu.mdd.policyengine.serializer;

import dk.itu.mdd.policyengine.serializer.AbstractPolicyEngineDslSyntacticSequencer;

@SuppressWarnings("all")
public class PolicyEngineDslSyntacticSequencer extends AbstractPolicyEngineDslSyntacticSequencer {
}
