/**
 * generated by Xtext
 */
package dk.itu.mdd.policyengine.serializer;

import dk.itu.mdd.policyengine.serializer.AbstractPolicyEngineDslSemanticSequencer;

@SuppressWarnings("all")
public class PolicyEngineDslSemanticSequencer extends AbstractPolicyEngineDslSemanticSequencer {
}
