/*
* generated by Xtext
*/
package dk.itu.mdd.policyengine.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PolicyEngineDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("dk/itu/mdd/policyengine/parser/antlr/internal/InternalPolicyEngineDsl.tokens");
	}
}
