/*
 * generated by Xtext
 */
package dk.itu.mdd.policyengine.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractPolicyEngineDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("platform:/resource/dk.itu.mdd.policyengine/model/PolicyEngine.ecore"));
		return result;
	}
}
