/*
* generated by Xtext
*/
package dk.itu.mdd.policyengine.ui.contentassist;

import dk.itu.mdd.policyengine.ui.contentassist.AbstractPeDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PeDslProposalProvider extends AbstractPeDslProposalProvider {

}
