/*
* generated by Xtext
*/
package dk.itu.mdd.policyengine;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PolicyEngineDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return dk.itu.mdd.policyengine.ui.internal.PolicyEngineDslActivator.getInstance().getInjector("dk.itu.mdd.policyengine.PolicyEngineDsl");
	}
	
}
