<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Time" nsURI="platform:/resource/dk.itu.mdd.policyengine/model/Time.ecore"
    nsPrefix="time">
  <eClassifiers xsi:type="ecore:EClass" name="Time">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minutes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schedule" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weekdays" upperBound="-1"
        eType="#//WeekDays"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//Time" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//Time" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WeekDays">
    <eLiterals name="MONDAY"/>
    <eLiterals name="TUESDAY" value="1"/>
    <eLiterals name="WEDENSDAY" value="2"/>
    <eLiterals name="THURSDAY" value="3"/>
    <eLiterals name="FRIDAY" value="4"/>
    <eLiterals name="SATURDAY" value="5"/>
    <eLiterals name="SUNDAY" value="6"/>
  </eClassifiers>
</ecore:EPackage>
