<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="building" nsURI="http://building/1.0" nsPrefix="building">
  <eClassifiers xsi:type="ecore:EClass" name="Door" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" lowerBound="2" upperBound="2"
        eType="#//Room" eOpposite="#//Room/doors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doorHandles" lowerBound="2"
        upperBound="2" eType="#//DoorHandle" eOpposite="#//DoorHandle/door"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="windows" upperBound="-1"
        eType="#//Window"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doors" upperBound="-1"
        eType="#//Door" eOpposite="#//Door/rooms"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Window" eSuperTypes="#//Identifiable #//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Construct" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" upperBound="-1"
        eType="#//Room" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="windows" upperBound="-1"
        eType="#//Window" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doors" upperBound="-1"
        eType="#//Door" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doorHandles" upperBound="-1"
        eType="#//DoorHandle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoorHandle" eSuperTypes="#//Identifiable #//PressureSensor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="door" lowerBound="1" eType="#//Door"
        eOpposite="#//Door/doorHandles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" unsettable="true" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constructs" upperBound="-1"
        eType="#//Construct" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AccessControl" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="LightSensor" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobilePhone" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alarm" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="MotionSensor" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="HumanMotionSensor" eSuperTypes="#//MotionSensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Computer" eSuperTypes="#//Sensor #//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="BikeTyreHolder" eSuperTypes="#//PressureSensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="PressureSensor" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="PetBottle" eSuperTypes="#//Sensor #//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoffeeMachine" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Calendar" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="KitchenTable" eSuperTypes="#//PressureSensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lamp" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="MeetingSchedule" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DishWasher" eSuperTypes="#//Sensor #//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Printer" eSuperTypes="#//Sensor #//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Radio" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ToiletSeat" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="SMS" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Blinds" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Phone" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="TemperatureSensor" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Heater" eSuperTypes="#//Actuator"/>
</ecore:EPackage>
