<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PolicyEngine" nsURI="http://policyengine/1.0" nsPrefix="policyengine">
  <eClassifiers xsi:type="ecore:EClass" name="Building" eSuperTypes="#//NamedElement #//HasActuators #//HasSensors">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defineComponents" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ctsSystem" eType="#//CTS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessControl" eType="#//AccessControl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calendarSystem" eType="#//CalendarSystem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="meetingScheduleSystem"
        eType="#//MeetingScheduleSystem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declareComponents" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//NamedElement #//HasActuators #//HasSensors">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//NamedElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LightSwitchActuator" eSuperTypes="#//SetsOnOffState"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//NamedElement #//HasSensors #//HasActuators">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declareComponents" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotionSensor" eSuperTypes="#//HasBooleanValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="TemperatureSensor" eSuperTypes="#//HasIntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="PressureSensor" eSuperTypes="#//HasIntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="TouchSensor" eSuperTypes="#//HasBooleanValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="WindowActuator" eSuperTypes="#//SetsOpenCloseState"/>
  <eClassifiers xsi:type="ecore:EClass" name="HumidifierActuator" eSuperTypes="#//SetsOnOffState"/>
  <eClassifiers xsi:type="ecore:EClass" name="LightSensor" eSuperTypes="#//HasIntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="CTS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="temperatureSensors" upperBound="-1"
        eType="#//Sensor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ctsActuators" upperBound="-1"
        eType="#//Actuator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessControl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessControlSensors" upperBound="-1"
        eType="#//Sensor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessControlDoorLockActuator"
        upperBound="-1" eType="#//Actuator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoorActuator" eSuperTypes="#//SetsOpenCloseState"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMSActuator" eSuperTypes="#//SetStringState"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalendarSystem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MeetingScheduleSystem"/>
  <eClassifiers xsi:type="ecore:EClass" name="RadiatorActuator" eSuperTypes="#//SetsOnOffState"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmokeSensor" eSuperTypes="#//HasIntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="HasSensors">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensors" eType="#//Sensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasActuators">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuators" eType="#//Actuator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CO2Sensor" eSuperTypes="#//HasIntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfraredLightSensor" eSuperTypes="#//HasIntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="HasIntegerValue" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasBooleanValue" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HumiditySensor" eSuperTypes="#//HasIntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseActuator" eSuperTypes="#//SetStringState"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudioAlarmActuator" eSuperTypes="#//SetsOnOffState"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetsOpenCloseState" eSuperTypes="#//Actuator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueState" eType="#//OpenClose"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetsOnOffState" eSuperTypes="#//Actuator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueState" eType="#//OnOff"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetStringState" eSuperTypes="#//Actuator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OpenClose">
    <eLiterals name="OPEN"/>
    <eLiterals name="CLOSE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OnOff">
    <eLiterals name="ON"/>
    <eLiterals name="OFF" value="1"/>
  </eClassifiers>
</ecore:EPackage>
