/*
* generated by Xtext
*/
package dk.itu.mdd.policyengine;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PolicyEngineDslStandaloneSetup extends PolicyEngineDslStandaloneSetupGenerated{

	public static void doSetup() {
		new PolicyEngineDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

