/*
 * generated by Xtext
 */
package dk.itu.mdd.policyengine;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PolicyEngineDslRuntimeModule extends dk.itu.mdd.policyengine.AbstractPolicyEngineDslRuntimeModule {

}
