<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PolicyEngine" nsURI="http://policyengine/1.0" nsPrefix="policyengine">
  <eClassifiers xsi:type="ecore:EClass" name="Building" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="floors" lowerBound="1"
        upperBound="-1" eType="#//Floor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ctsSystem" eType="#//CTS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessControl" eType="#//AccessControl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="smsSystem" eType="#//SMSSystem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calendarSystem" eType="#//CalendarSystem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="meetingScheduleSystem"
        eType="#//MeetingScheduleSystem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//NamedElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LightSwitchActuator" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Floor" eSuperTypes="#//NamedElement #//HasSensors #//HasActuators">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" lowerBound="1" upperBound="-1"
        eType="#//Room" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotionSensor" eSuperTypes="#//HasBooleanValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="TemperatureSensor" eSuperTypes="#//HasIntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="PressureSensor" eSuperTypes="#//HasIntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="TouchSensor" eSuperTypes="#//HasBooleanValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="WindowActuator" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Room" eSuperTypes="#//NamedElement #//HasActuators #//HasSensors"/>
  <eClassifiers xsi:type="ecore:EClass" name="HumidifierActuator" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="LightSensor" eSuperTypes="#//HasIntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="CTS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="temperatureSensors" upperBound="-1"
        eType="#//Sensor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ctsActuators" upperBound="-1"
        eType="#//Actuator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessControl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessControlSensors" upperBound="-1"
        eType="#//Sensor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessControlDoorLockActuator"
        upperBound="-1" eType="#//Actuator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoorActuator" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMSSystem"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalendarSystem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MeetingScheduleSystem"/>
  <eClassifiers xsi:type="ecore:EClass" name="RadiatorKnobActuator" eSuperTypes="#//Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmokeSensor" eSuperTypes="#//HasIntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="HasSensors">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensors" eType="#//Sensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasActuators">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuators" eType="#//Actuator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CO2Sensor" eSuperTypes="#//HasIntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfraredLightSensor" eSuperTypes="#//HasIntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="HasIntegerValue" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasBooleanValue" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HumiditySensor" eSuperTypes="#//HasIntegerValue"/>
</ecore:EPackage>
