/*
* generated by Xtext
*/
package dk.itu.mdd.policyengine.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import dk.itu.mdd.policyengine.services.PeDslGrammarAccess;

public class PeDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PeDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected dk.itu.mdd.policyengine.parser.antlr.internal.InternalPeDslParser createParser(XtextTokenStream stream) {
		return new dk.itu.mdd.policyengine.parser.antlr.internal.InternalPeDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public PeDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PeDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
