/*
 * generated by Xtext
 */
package dk.itu.mdd.policyengine.ui.contentassist

import dk.itu.mdd.policyengine.ui.contentassist.AbstractPolicyEngineDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class PolicyEngineDslProposalProvider extends AbstractPolicyEngineDslProposalProvider {
}
