/*
 * generated by Xtext
 */
package dk.itu.mdd.policyengine.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PolicyEngineDslUiModule extends dk.itu.mdd.policyengine.ui.AbstractPolicyEngineDslUiModule {
	public PolicyEngineDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
